In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('house.csv')
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
df2=df.loc[5:10,['LotArea','Street']]
df2=df2.reset_index(drop=True)
df2

LotArea Street
0    14115   Pave
1    10084   Pave
2    10382   Pave
3     6120   Pave
4     7420   Pave
5    11200   Pave

In [ ]:
# 取所有
df3=df.loc[:,:]
df3

In [ ]:
# 取5到10行
df4=df.loc[5:10,:]
df4

In [ ]:
# 按行号取
df5=df.loc[[5,8]]
df5

In [ ]:
# 按行号取5到10行
df6=df.loc[[5,6,7,8,9,10,5,6,7,8,9,10]]
df6

In [ ]:
# 按条件取
# 条件写在行里，多个条件用小括号括起来
c1=(df['LotArea']>20000) & (df['SalePrice']<200000)
df7=df.loc[c1]

In [ ]:
# 改数据
df.loc[2,'LotArea']=1000
df

In [ ]:
#聚合:最大值max，最小值min，平均值mean，总和sum，个数count， 中位数median，方差var，标准差std
df.loc[:,'LotArea'].max()

In [ ]:
df.max(numeric_only=True)

In [ ]:
#分组
df8=df.groupby('YearBuilt').mean(numeric_only=True)
df8.loc[:,['SalePrice']]

In [ ]:
#合并
df10=pd.read_excel('house.xlsx')
df10

In [ ]:
#列合并
df9=pd.concat([df, df10],axis=1)
df9

In [ ]:
#行合并
df11=pd.concat([df, df10],axis=0)
df11=df11.reset_index(drop=True)
df11

In [ ]:
df11.loc[0]

In [ ]:
df11=pd.read_excel('BASEDATA.xlsx',sheet_name='支付')
df11

In [ ]:
df12=pd.read_excel('BASEDATA.xlsx',sheet_name='客户')
df12

In [ ]:
#inner left
df13=df11.merge(df12,'inner',left_on='customer_id',right_on='customer_id')
df13.loc[0:3]

In [3]:
import numpy as np

In [16]:
df20=df.loc[:,['GrLivArea','OverallQual']]
x=df20.to_numpy()
x.shape

(1460, 2)

In [13]:
x0=x[0:100,:]
x0

array([[1710,    7],
       [1262,    6],
       [1786,    7],
       [1717,    7],
       [2198,    8],
       [1362,    5],
       [1694,    8],
       [2090,    7],
       [1774,    7],
       [1077,    5],
       [1040,    5],
       [2324,    9],
       [ 912,    5],
       [1494,    7],
       [1253,    6],
       [ 854,    7],
       [1004,    6],
       [1296,    4],
       [1114,    5],
       [1339,    5],
       [2376,    8],
       [1108,    7],
       [1795,    8],
       [1060,    5],
       [1060,    5],
       [1600,    8],
       [ 900,    5],
       [1704,    8],
       [1600,    5],
       [ 520,    4],
       [1317,    4],
       [1228,    5],
       [1234,    8],
       [1700,    5],
       [1561,    9],
       [2452,    8],
       [1097,    5],
       [1297,    5],
       [1057,    5],
       [1152,    4],
       [1324,    6],
       [1328,    5],
       [ 884,    5],
       [ 938,    5],
       [1150,    5],
       [1752,    9],
       [2149,    7],
       [1656,

In [24]:
w=np.random.randint(0, 100, (2,100))
w0=np.random.randint(0, 100, (100,))
w.shape

(2, 100)

In [27]:
y = x @ w + w0
y.shape

(1460, 100)

In [33]:
import torch
import torch.nn as nn

In [35]:
x.dtype

dtype('int64')

In [38]:
x=x.astype(np.float32)
XT=torch.from_numpy(x)
L1=nn.Linear(2,100)
Y=L1(XT)
Y.shape

torch.Size([1460, 100])

In [39]:
A=np.random.randint(0,100,(50,50))
A

array([[98, 46, 90, ..., 37, 19, 44],
       [79, 30, 13, ..., 39, 57, 58],
       [67, 24, 94, ..., 93, 35,  4],
       ...,
       [ 3, 18, 94, ..., 22, 73, 24],
       [ 0, 45, 35, ..., 58, 73, 30],
       [81, 42, 81, ..., 66, 53, 68]])

In [40]:
K=np.random.randint(0,10,(3,3))
K

array([[9, 6, 7],
       [9, 1, 9],
       [3, 7, 0]])

In [54]:
t1=np.arange(0,3,1)
t2=t1.repeat(3)
t3=np.tile(t2,2)

t4=np.tile(t1,3)
t5= t4 + 2
t6=np.concatenate([t4,t5])
t6

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 2, 3, 4, 2, 3, 4, 2, 3, 4])

In [41]:
(A[0:3,0:3]*K).sum()

3015

In [43]:
(A[0:3,2:5]*K).sum()

1910

In [60]:
t7 = A[t3,t6]
K1=K.flatten()
K2=np.tile(K1,2)
t8=t7*K2
t9=t8.reshape(2,9)
t9.sum(axis=1)

array([3015, 1910])

In [71]:
A=A.astype(np.float32)
A=A.reshape(1,50,50)
AT=torch.from_numpy(A)
c1=nn.Conv2d(1,5,3,2,0)
AC=c1(AT)
AC

tensor([[[-20.9949, -55.8678,   8.5364,  ...,  20.4329,   9.7066, -24.6985],
         [-10.3417, -17.2834, -15.6140,  ...,  -7.5204,   3.4494,   3.1021],
         [  7.1164, -17.2866, -18.0844,  ...,   2.3082,   7.6182,  -2.6949],
         ...,
         [ -2.7577, -12.7257, -14.5655,  ...,  -8.8944,  -6.0419, -19.4145],
         [ 23.1809,  15.2929, -25.1380,  ...,   6.9845,  -8.6989,   2.2926],
         [ 15.9383,  14.2602, -23.7692,  ...,  -2.7227,   1.8402, -11.4940]],

        [[-18.7763,  -7.5096,  41.5318,  ...,  29.6205,   3.4095,  35.9305],
         [ 33.0659, -10.7545,  35.5485,  ...,  15.5651,  33.8016,  -4.9778],
         [ 52.8441,   2.0752,  28.6818,  ...,  19.2111,   7.5186,  19.8498],
         ...,
         [  7.8851, -22.0961,  -1.3943,  ...,  23.2671,   8.6812,  17.6826],
         [ 33.2430,  12.1750,   5.6916,  ...,  26.6946,  -6.0963,  58.3492],
         [ 45.3525,  29.3166,   7.2236,  ...,  38.6211,  -4.4178,  23.9061]],

        [[-17.8306, -28.6590, -30.3182,  ...

In [2]:
import torch
if torch.cuda.is_available():
    print("GPU加速可用")
else:
    print("GPU加速不可用")

if torch.cuda.is_available():
    print(f"CUDA is available: {torch.cuda.is_available()}")
    print(f"CUDA device count: {torch.cuda.device_count()}")
    print(f"CUDA device name: {torch.cuda.get_device_name(0)}")

GPU加速可用
CUDA is available: True
CUDA device count: 1
CUDA device name: GeForce GTX 1060 6GB
